/**
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import type { Challenge } from './types.js';

export const CHALLENGES: Challenge[] = [
  // Beginner - Basics (10 challenges)
  {
    id: 'basic-hello',
    title: 'Hello Gemini CLI',
    description: 'Write a prompt that asks Gemini to say hello',
    difficulty: 'beginner',
    category: 'basics',
    estimatedTime: '2 minutes',
    points: 10,
    hints: ['Use a simple greeting prompt', 'Ask Gemini directly'],
    solution: 'Say hello to me',
    solutionExplanation: 'A simple, direct prompt asking Gemini to greet you.',
    testCases: [
      { name: 'Contains greeting', input: 'hello', expectedOutput: 'hello' },
    ],
  },
  {
    id: 'basic-file-read',
    title: 'Read a File',
    description: 'Ask Gemini to read the contents of a specific file',
    difficulty: 'beginner',
    category: 'file-operations',
    estimatedTime: '3 minutes',
    points: 15,
    hints: ['Mention the file name', 'Ask to read or show the file'],
    solution: 'Read the file README.md',
    solutionExplanation: 'Specify the file you want to read.',
    testCases: [{ name: 'Mentions file', input: 'README', expectedOutput: 'README' }],
  },
  {
    id: 'basic-create-file',
    title: 'Create a New File',
    description: 'Ask Gemini to create a new file with specific content',
    difficulty: 'beginner',
    category: 'file-operations',
    estimatedTime: '3 minutes',
    points: 15,
    hints: ['Specify file name and content', 'Use "create" or "write"'],
    solution: 'Create a file called test.txt with content "Hello World"',
    solutionExplanation: 'Clearly state the filename and desired content.',
    testCases: [
      { name: 'Mentions create', input: 'create', expectedOutput: 'create' },
    ],
  },
  {
    id: 'basic-list-files',
    title: 'List Files',
    description: 'Ask Gemini to list files in the current directory',
    difficulty: 'beginner',
    category: 'file-operations',
    estimatedTime: '2 minutes',
    points: 10,
    hints: ['Use "list" or "show"', 'Specify "files" or "directory"'],
    solution: 'List all files in the current directory',
    solutionExplanation: 'Request a listing of files.',
    testCases: [{ name: 'List files', input: 'list', expectedOutput: 'list' }],
  },
  {
    id: 'basic-search',
    title: 'Search in Files',
    description: 'Ask Gemini to search for a specific term in files',
    difficulty: 'beginner',
    category: 'file-operations',
    estimatedTime: '4 minutes',
    points: 20,
    hints: ['Specify search term', 'Mention which files to search'],
    solution: 'Search for "function" in all JavaScript files',
    solutionExplanation: 'Specify what to search for and where.',
    testCases: [{ name: 'Search term', input: 'search', expectedOutput: 'search' }],
  },
  {
    id: 'basic-explain',
    title: 'Explain Code',
    description: 'Ask Gemini to explain what a piece of code does',
    difficulty: 'beginner',
    category: 'basics',
    estimatedTime: '3 minutes',
    points: 15,
    hints: ['Use "explain"', 'Provide code context'],
    solution: 'Explain what this function does: function add(a, b) { return a + b; }',
    solutionExplanation: 'Ask for an explanation of specific code.',
    testCases: [{ name: 'Explain code', input: 'explain', expectedOutput: 'explain' }],
  },
  {
    id: 'basic-refactor',
    title: 'Simple Refactoring',
    description: 'Ask Gemini to improve code readability',
    difficulty: 'beginner',
    category: 'basics',
    estimatedTime: '5 minutes',
    points: 20,
    hints: ['Mention "refactor" or "improve"', 'Specify the code'],
    solution: 'Refactor this code to be more readable: let x=a+b;console.log(x);',
    solutionExplanation: 'Request code improvement with specific code provided.',
    testCases: [
      { name: 'Refactor code', input: 'refactor', expectedOutput: 'refactor' },
    ],
  },
  {
    id: 'basic-command',
    title: 'Run a Command',
    description: 'Ask Gemini to execute a shell command',
    difficulty: 'beginner',
    category: 'basics',
    estimatedTime: '3 minutes',
    points: 15,
    hints: ['Use "run" or "execute"', 'Specify the command'],
    solution: 'Run the command "npm test"',
    solutionExplanation: 'Request execution of a specific command.',
    testCases: [{ name: 'Run command', input: 'run', expectedOutput: 'run' }],
  },
  {
    id: 'basic-documentation',
    title: 'Generate Documentation',
    description: 'Ask Gemini to write JSDoc for a function',
    difficulty: 'beginner',
    category: 'basics',
    estimatedTime: '5 minutes',
    points: 20,
    hints: ['Mention "documentation" or "JSDoc"', 'Provide function signature'],
    solution: 'Add JSDoc to: function calculate(x, y) { return x * y; }',
    solutionExplanation: 'Request documentation for specific code.',
    testCases: [{ name: 'Add docs', input: 'JSDoc', expectedOutput: 'JSDoc' }],
  },
  {
    id: 'basic-git',
    title: 'Git Status',
    description: 'Ask Gemini to show git status',
    difficulty: 'beginner',
    category: 'basics',
    estimatedTime: '2 minutes',
    points: 10,
    hints: ['Use "git"', 'Ask for "status"'],
    solution: 'Show me the git status',
    solutionExplanation: 'Request current git repository status.',
    testCases: [{ name: 'Git status', input: 'git', expectedOutput: 'git' }],
  },

  // Intermediate - File Operations & Data Processing (15 challenges)
  {
    id: 'file-batch-rename',
    title: 'Batch Rename Files',
    description: 'Rename multiple files following a pattern',
    difficulty: 'intermediate',
    category: 'file-operations',
    estimatedTime: '8 minutes',
    points: 30,
    hints: ['Specify pattern', 'Mention file selection criteria'],
    solution: 'Rename all .txt files to add "-backup" before the extension',
    solutionExplanation: 'Describe the pattern transformation clearly.',
    testCases: [{ name: 'Rename pattern', input: 'rename', expectedOutput: 'rename' }],
  },
  {
    id: 'file-merge',
    title: 'Merge Files',
    description: 'Combine multiple files into one',
    difficulty: 'intermediate',
    category: 'file-operations',
    estimatedTime: '6 minutes',
    points: 25,
    hints: ['List files to merge', 'Specify output file'],
    solution: 'Merge file1.txt and file2.txt into combined.txt',
    solutionExplanation: 'Specify source files and destination.',
    testCases: [{ name: 'Merge files', input: 'merge', expectedOutput: 'merge' }],
  },
  {
    id: 'data-csv-parse',
    title: 'Parse CSV Data',
    description: 'Extract specific columns from a CSV file',
    difficulty: 'intermediate',
    category: 'data-processing',
    estimatedTime: '10 minutes',
    points: 35,
    hints: ['Specify CSV file', 'Name the columns to extract'],
    solution: 'Extract "name" and "email" columns from users.csv',
    solutionExplanation: 'Identify the file and desired columns.',
    testCases: [{ name: 'Parse CSV', input: 'csv', expectedOutput: 'csv' }],
  },
  {
    id: 'data-json-transform',
    title: 'Transform JSON',
    description: 'Convert JSON data to a different structure',
    difficulty: 'intermediate',
    category: 'data-processing',
    estimatedTime: '12 minutes',
    points: 40,
    hints: ['Show input structure', 'Describe output structure'],
    solution:
      'Transform this JSON array to object: [{"id":1,"name":"Alice"}] to {"1":"Alice"}',
    solutionExplanation: 'Clearly describe both input and output formats.',
    testCases: [{ name: 'Transform JSON', input: 'JSON', expectedOutput: 'JSON' }],
  },
  {
    id: 'data-filter',
    title: 'Filter Data',
    description: 'Filter array based on criteria',
    difficulty: 'intermediate',
    category: 'data-processing',
    estimatedTime: '8 minutes',
    points: 30,
    hints: ['Specify data source', 'Define filter criteria'],
    solution: 'Filter users array to only include those with age > 18',
    solutionExplanation: 'State the filtering condition clearly.',
    testCases: [{ name: 'Filter data', input: 'filter', expectedOutput: 'filter' }],
  },
  {
    id: 'file-organize',
    title: 'Organize Files by Type',
    description: 'Move files into folders based on their extension',
    difficulty: 'intermediate',
    category: 'file-operations',
    estimatedTime: '10 minutes',
    points: 35,
    hints: ['Group by extension', 'Create folders as needed'],
    solution: 'Organize files into folders by extension (images/, docs/, etc.)',
    solutionExplanation: 'Describe the organization structure.',
    testCases: [
      { name: 'Organize files', input: 'organize', expectedOutput: 'organize' },
    ],
  },
  {
    id: 'data-aggregate',
    title: 'Aggregate Data',
    description: 'Calculate sum, average, or count from dataset',
    difficulty: 'intermediate',
    category: 'data-processing',
    estimatedTime: '10 minutes',
    points: 35,
    hints: ['Specify aggregation function', 'Name the field'],
    solution: 'Calculate the average price from products.json',
    solutionExplanation: 'Specify the calculation and data source.',
    testCases: [
      { name: 'Aggregate data', input: 'average', expectedOutput: 'average' },
    ],
  },
  {
    id: 'file-diff',
    title: 'Compare Files',
    description: 'Find differences between two files',
    difficulty: 'intermediate',
    category: 'file-operations',
    estimatedTime: '8 minutes',
    points: 30,
    hints: ['Name both files', 'Specify comparison type'],
    solution: 'Show differences between version1.txt and version2.txt',
    solutionExplanation: 'Request a diff between two specific files.',
    testCases: [
      { name: 'Compare files', input: 'differences', expectedOutput: 'differences' },
    ],
  },
  {
    id: 'data-sort',
    title: 'Sort Data',
    description: 'Sort array by specific field',
    difficulty: 'intermediate',
    category: 'data-processing',
    estimatedTime: '8 minutes',
    points: 30,
    hints: ['Specify sort field', 'Mention order (asc/desc)'],
    solution: 'Sort products by price in descending order',
    solutionExplanation: 'State the field and sort direction.',
    testCases: [{ name: 'Sort data', input: 'sort', expectedOutput: 'sort' }],
  },
  {
    id: 'file-backup',
    title: 'Create Backup',
    description: 'Create a backup of important files',
    difficulty: 'intermediate',
    category: 'file-operations',
    estimatedTime: '10 minutes',
    points: 35,
    hints: ['Specify files to backup', 'Name backup location'],
    solution: 'Create backup of all .js files in src/ to backup/ folder',
    solutionExplanation: 'Define source files and backup destination.',
    testCases: [{ name: 'Create backup', input: 'backup', expectedOutput: 'backup' }],
  },
  {
    id: 'data-validate',
    title: 'Validate Data',
    description: 'Check if data matches expected schema',
    difficulty: 'intermediate',
    category: 'data-processing',
    estimatedTime: '12 minutes',
    points: 40,
    hints: ['Define schema requirements', 'Specify validation rules'],
    solution: 'Validate that all users have email and password fields',
    solutionExplanation: 'List required fields and validation rules.',
    testCases: [
      { name: 'Validate data', input: 'validate', expectedOutput: 'validate' },
    ],
  },
  {
    id: 'file-template',
    title: 'Generate from Template',
    description: 'Create files using a template with variables',
    difficulty: 'intermediate',
    category: 'file-operations',
    estimatedTime: '10 minutes',
    points: 35,
    hints: ['Show template', 'Provide variable values'],
    solution: 'Create component.jsx from template with name="Button"',
    solutionExplanation: 'Specify template and variable substitutions.',
    testCases: [
      { name: 'Use template', input: 'template', expectedOutput: 'template' },
    ],
  },
  {
    id: 'data-group',
    title: 'Group Data',
    description: 'Group items by a specific field',
    difficulty: 'intermediate',
    category: 'data-processing',
    estimatedTime: '10 minutes',
    points: 35,
    hints: ['Specify grouping field', 'Describe output format'],
    solution: 'Group users by country',
    solutionExplanation: 'State which field to group by.',
    testCases: [{ name: 'Group data', input: 'group', expectedOutput: 'group' }],
  },
  {
    id: 'file-compress',
    title: 'Compress Files',
    description: 'Create a compressed archive of files',
    difficulty: 'intermediate',
    category: 'file-operations',
    estimatedTime: '8 minutes',
    points: 30,
    hints: ['Specify files to compress', 'Name archive file'],
    solution: 'Compress all files in dist/ to release.zip',
    solutionExplanation: 'Specify source and archive name.',
    testCases: [
      { name: 'Compress files', input: 'compress', expectedOutput: 'compress' },
    ],
  },
  {
    id: 'data-deduplicate',
    title: 'Remove Duplicates',
    description: 'Remove duplicate entries from dataset',
    difficulty: 'intermediate',
    category: 'data-processing',
    estimatedTime: '10 minutes',
    points: 35,
    hints: ['Specify uniqueness criteria', 'Mention data source'],
    solution: 'Remove duplicate users based on email address',
    solutionExplanation: 'Define what makes an entry unique.',
    testCases: [
      { name: 'Remove duplicates', input: 'duplicate', expectedOutput: 'duplicate' },
    ],
  },

  // Advanced - Testing, Debugging, API Integration (15 challenges)
  {
    id: 'test-unit',
    title: 'Write Unit Tests',
    description: 'Generate unit tests for a function',
    difficulty: 'advanced',
    category: 'testing',
    estimatedTime: '15 minutes',
    points: 50,
    hints: ['Provide function to test', 'Specify test framework'],
    solution:
      'Write Vitest tests for: function multiply(a, b) { return a * b; }',
    solutionExplanation: 'Request tests with specific framework.',
    testCases: [{ name: 'Unit tests', input: 'test', expectedOutput: 'test' }],
  },
  {
    id: 'test-integration',
    title: 'Integration Tests',
    description: 'Write integration tests for API endpoints',
    difficulty: 'advanced',
    category: 'testing',
    estimatedTime: '20 minutes',
    points: 60,
    hints: ['Describe API endpoints', 'Include test scenarios'],
    solution: 'Write integration tests for POST /api/users endpoint',
    solutionExplanation: 'Specify endpoints and test cases.',
    testCases: [
      { name: 'Integration tests', input: 'integration', expectedOutput: 'integration' },
    ],
  },
  {
    id: 'debug-error',
    title: 'Debug Runtime Error',
    description: 'Find and fix a runtime error',
    difficulty: 'advanced',
    category: 'debugging',
    estimatedTime: '18 minutes',
    points: 55,
    hints: ['Provide error message', 'Show relevant code'],
    solution: 'Fix: TypeError: Cannot read property "name" of undefined',
    solutionExplanation: 'Include error details and code context.',
    testCases: [{ name: 'Debug error', input: 'TypeError', expectedOutput: 'TypeError' }],
  },
  {
    id: 'api-fetch',
    title: 'Fetch API Data',
    description: 'Call an API and process the response',
    difficulty: 'advanced',
    category: 'api-integration',
    estimatedTime: '15 minutes',
    points: 50,
    hints: ['Specify API endpoint', 'Describe response handling'],
    solution: 'Fetch data from https://api.example.com/users and extract names',
    solutionExplanation: 'Include API URL and desired data extraction.',
    testCases: [{ name: 'API fetch', input: 'fetch', expectedOutput: 'fetch' }],
  },
  {
    id: 'api-post',
    title: 'POST to API',
    description: 'Send data to an API endpoint',
    difficulty: 'advanced',
    category: 'api-integration',
    estimatedTime: '15 minutes',
    points: 50,
    hints: ['Specify endpoint and method', 'Include request body'],
    solution: 'POST {"name":"Alice"} to https://api.example.com/users',
    solutionExplanation: 'Include HTTP method, endpoint, and data.',
    testCases: [{ name: 'API post', input: 'POST', expectedOutput: 'POST' }],
  },
  {
    id: 'test-coverage',
    title: 'Improve Test Coverage',
    description: 'Add tests to reach 90% coverage',
    difficulty: 'advanced',
    category: 'testing',
    estimatedTime: '25 minutes',
    points: 70,
    hints: ['Check current coverage', 'Identify untested paths'],
    solution: 'Add tests to cover all branches in auth.js',
    solutionExplanation: 'Specify target file and coverage goal.',
    testCases: [
      { name: 'Test coverage', input: 'coverage', expectedOutput: 'coverage' },
    ],
  },
  {
    id: 'debug-memory',
    title: 'Fix Memory Leak',
    description: 'Identify and fix a memory leak',
    difficulty: 'advanced',
    category: 'debugging',
    estimatedTime: '25 minutes',
    points: 70,
    hints: ['Look for event listeners', 'Check for circular references'],
    solution: 'Find memory leak in event handler that is not cleaned up',
    solutionExplanation: 'Describe the leak pattern to find.',
    testCases: [
      { name: 'Memory leak', input: 'memory', expectedOutput: 'memory' },
    ],
  },
  {
    id: 'api-auth',
    title: 'API Authentication',
    description: 'Implement OAuth authentication for API',
    difficulty: 'advanced',
    category: 'api-integration',
    estimatedTime: '20 minutes',
    points: 60,
    hints: ['Specify auth type', 'Include credentials handling'],
    solution: 'Add OAuth2 authentication to API client',
    solutionExplanation: 'Specify authentication method and implementation.',
    testCases: [{ name: 'API auth', input: 'OAuth', expectedOutput: 'OAuth' }],
  },
  {
    id: 'test-mock',
    title: 'Mock Dependencies',
    description: 'Create mocks for external dependencies',
    difficulty: 'advanced',
    category: 'testing',
    estimatedTime: '18 minutes',
    points: 55,
    hints: ['Identify dependencies', 'Use mocking library'],
    solution: 'Mock database calls in user service tests',
    solutionExplanation: 'Specify what to mock and how.',
    testCases: [{ name: 'Mock deps', input: 'mock', expectedOutput: 'mock' }],
  },
  {
    id: 'debug-performance',
    title: 'Optimize Performance',
    description: 'Find and fix performance bottleneck',
    difficulty: 'advanced',
    category: 'debugging',
    estimatedTime: '25 minutes',
    points: 70,
    hints: ['Profile the code', 'Look for N+1 queries'],
    solution: 'Optimize function that loops over large dataset',
    solutionExplanation: 'Describe the performance issue.',
    testCases: [
      { name: 'Performance', input: 'optimize', expectedOutput: 'optimize' },
    ],
  },
  {
    id: 'api-retry',
    title: 'API Retry Logic',
    description: 'Implement retry logic for failed API calls',
    difficulty: 'advanced',
    category: 'api-integration',
    estimatedTime: '18 minutes',
    points: 55,
    hints: ['Define retry strategy', 'Handle exponential backoff'],
    solution: 'Add retry logic with 3 attempts and exponential backoff',
    solutionExplanation: 'Specify retry count and delay strategy.',
    testCases: [{ name: 'Retry logic', input: 'retry', expectedOutput: 'retry' }],
  },
  {
    id: 'test-e2e',
    title: 'End-to-End Tests',
    description: 'Write E2E tests for user flow',
    difficulty: 'advanced',
    category: 'testing',
    estimatedTime: '25 minutes',
    points: 70,
    hints: ['Define user journey', 'Use E2E framework'],
    solution: 'Write Playwright tests for login → dashboard → logout flow',
    solutionExplanation: 'Describe full user journey to test.',
    testCases: [{ name: 'E2E tests', input: 'Playwright', expectedOutput: 'Playwright' }],
  },
  {
    id: 'debug-race',
    title: 'Fix Race Condition',
    description: 'Identify and fix a race condition',
    difficulty: 'advanced',
    category: 'debugging',
    estimatedTime: '25 minutes',
    points: 70,
    hints: ['Look for async operations', 'Check for shared state'],
    solution: 'Fix race condition in concurrent file writes',
    solutionExplanation: 'Describe the race condition scenario.',
    testCases: [{ name: 'Race condition', input: 'race', expectedOutput: 'race' }],
  },
  {
    id: 'api-pagination',
    title: 'Implement Pagination',
    description: 'Add pagination to API endpoint',
    difficulty: 'advanced',
    category: 'api-integration',
    estimatedTime: '20 minutes',
    points: 60,
    hints: ['Define page size', 'Handle page parameters'],
    solution: 'Add pagination to /api/users with limit=10 and offset',
    solutionExplanation: 'Specify pagination strategy and parameters.',
    testCases: [
      { name: 'Pagination', input: 'pagination', expectedOutput: 'pagination' },
    ],
  },
  {
    id: 'test-snapshot',
    title: 'Snapshot Testing',
    description: 'Add snapshot tests for UI components',
    difficulty: 'advanced',
    category: 'testing',
    estimatedTime: '18 minutes',
    points: 55,
    hints: ['Specify components', 'Use snapshot framework'],
    solution: 'Add snapshot tests for Button and Card components',
    solutionExplanation: 'List components to snapshot test.',
    testCases: [
      { name: 'Snapshot test', input: 'snapshot', expectedOutput: 'snapshot' },
    ],
  },

  // Expert - Optimization & Architecture (10 challenges)
  {
    id: 'opt-bundle',
    title: 'Optimize Bundle Size',
    description: 'Reduce JavaScript bundle size by 30%',
    difficulty: 'expert',
    category: 'optimization',
    estimatedTime: '30 minutes',
    points: 100,
    hints: ['Analyze bundle', 'Remove unused code', 'Use code splitting'],
    solution: 'Analyze webpack bundle and implement code splitting',
    solutionExplanation: 'Describe optimization strategies.',
    testCases: [{ name: 'Bundle size', input: 'bundle', expectedOutput: 'bundle' }],
  },
  {
    id: 'arch-microservices',
    title: 'Design Microservices',
    description: 'Design microservices architecture for e-commerce',
    difficulty: 'expert',
    category: 'architecture',
    estimatedTime: '40 minutes',
    points: 120,
    hints: ['Define services', 'Describe communication', 'Plan data flow'],
    solution:
      'Design services for: users, products, orders, payments, notifications',
    solutionExplanation: 'Outline service boundaries and interactions.',
    testCases: [
      { name: 'Microservices', input: 'services', expectedOutput: 'services' },
    ],
  },
  {
    id: 'opt-database',
    title: 'Database Query Optimization',
    description: 'Optimize slow database queries',
    difficulty: 'expert',
    category: 'optimization',
    estimatedTime: '35 minutes',
    points: 110,
    hints: ['Add indexes', 'Optimize joins', 'Use query analysis'],
    solution: 'Optimize query with multiple joins on large tables',
    solutionExplanation: 'Describe query and optimization approach.',
    testCases: [{ name: 'Query opt', input: 'query', expectedOutput: 'query' }],
  },
  {
    id: 'arch-caching',
    title: 'Implement Caching Strategy',
    description: 'Design multi-level caching architecture',
    difficulty: 'expert',
    category: 'architecture',
    estimatedTime: '35 minutes',
    points: 110,
    hints: ['Define cache layers', 'Set TTL policies', 'Plan invalidation'],
    solution: 'Design caching with Redis, CDN, and browser cache',
    solutionExplanation: 'Describe caching layers and strategies.',
    testCases: [{ name: 'Caching', input: 'cache', expectedOutput: 'cache' }],
  },
  {
    id: 'opt-rendering',
    title: 'Optimize Rendering Performance',
    description: 'Improve React component rendering by 50%',
    difficulty: 'expert',
    category: 'optimization',
    estimatedTime: '30 minutes',
    points: 100,
    hints: ['Use memoization', 'Optimize re-renders', 'Virtual scrolling'],
    solution: 'Use React.memo, useMemo, and virtual scrolling for large lists',
    solutionExplanation: 'List React optimization techniques.',
    testCases: [
      { name: 'Rendering', input: 'rendering', expectedOutput: 'rendering' },
    ],
  },
  {
    id: 'arch-event-driven',
    title: 'Event-Driven Architecture',
    description: 'Design event-driven system with message queues',
    difficulty: 'expert',
    category: 'architecture',
    estimatedTime: '40 minutes',
    points: 120,
    hints: ['Choose message broker', 'Define events', 'Plan consumers'],
    solution: 'Design event system with RabbitMQ for order processing',
    solutionExplanation: 'Describe event flow and message handling.',
    testCases: [{ name: 'Event-driven', input: 'event', expectedOutput: 'event' }],
  },
  {
    id: 'opt-lazy-loading',
    title: 'Implement Lazy Loading',
    description: 'Add lazy loading to reduce initial load time',
    difficulty: 'expert',
    category: 'optimization',
    estimatedTime: '30 minutes',
    points: 100,
    hints: ['Route-based splitting', 'Component lazy loading', 'Image lazy loading'],
    solution: 'Implement React.lazy for routes and IntersectionObserver for images',
    solutionExplanation: 'Describe lazy loading implementation.',
    testCases: [{ name: 'Lazy loading', input: 'lazy', expectedOutput: 'lazy' }],
  },
  {
    id: 'arch-scalability',
    title: 'Design for Scale',
    description: 'Design system to handle 1M daily users',
    difficulty: 'expert',
    category: 'architecture',
    estimatedTime: '45 minutes',
    points: 130,
    hints: ['Load balancing', 'Database sharding', 'Horizontal scaling'],
    solution: 'Design with load balancers, read replicas, and CDN',
    solutionExplanation: 'Describe scalability architecture.',
    testCases: [{ name: 'Scalability', input: 'scale', expectedOutput: 'scale' }],
  },
  {
    id: 'opt-memory',
    title: 'Memory Optimization',
    description: 'Reduce application memory usage by 40%',
    difficulty: 'expert',
    category: 'optimization',
    estimatedTime: '35 minutes',
    points: 110,
    hints: ['Profile memory', 'Reduce object creation', 'Use weak references'],
    solution: 'Use memory profiler to find leaks and optimize data structures',
    solutionExplanation: 'Describe memory optimization techniques.',
    testCases: [{ name: 'Memory opt', input: 'memory', expectedOutput: 'memory' }],
  },
  {
    id: 'arch-resilience',
    title: 'Design for Resilience',
    description: 'Implement circuit breaker and fallback patterns',
    difficulty: 'expert',
    category: 'architecture',
    estimatedTime: '40 minutes',
    points: 120,
    hints: ['Circuit breaker states', 'Fallback strategies', 'Health checks'],
    solution: 'Implement circuit breaker with fallback and retry logic',
    solutionExplanation: 'Describe resilience patterns and implementation.',
    testCases: [
      { name: 'Resilience', input: 'circuit breaker', expectedOutput: 'circuit breaker' },
    ],
  },
];
