name: 'Setup NPMRC'
description: 'Sets up NPMRC with all the correct repos for readonly access.'

inputs:
  github-token:
    description: 'the github token'
    required: true

runs:
  using: 'composite'
  steps:
    - name: 'Configure .npmrc'
      shell: 'bash'
      run: |-
        echo ""@google-gemini:registry=https://npm.pkg.github.com"" > ~/.npmrc
        echo ""//npm.pkg.github.com/:_authToken=${{ inputs.github-token }}"" >> ~/.npmrc
        echo ""@google:registry=https://wombat-dressing-room.appspot.com"" >> ~/.npmrc
