/**
 * @license
 * Copyright 2025 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import ts from 'typescript';
import path from 'node:path';

/**
 * Result of a syntax verification check.
 */
export interface SyntaxVerificationResult {
  valid: boolean;
  error?: string;
}

/**
 * Verifies the syntax of the provided content using the TypeScript Compiler API.
 * Currently supports .ts, .tsx, .js, and .jsx files.
 *
 * @param content The code content to verify.
 * @param filePath The path to the file (used to determine the script target and language service).
 * @returns A SyntaxVerificationResult indicating if the code is syntactically valid.
 */
export function verifySyntax(
  content: string,
  filePath: string,
): SyntaxVerificationResult {
  const ext = path.extname(filePath).toLowerCase();

  // Only verify TS/JS files for now.
  if (!['.ts', '.tsx', '.js', '.jsx'].includes(ext)) {
    return { valid: true };
  }

  const scriptKind = getScriptKind(ext);
  const sourceFile = ts.createSourceFile(
    filePath,
    content,
    ts.ScriptTarget.Latest,
    true, // setParentNodes
    scriptKind,
  );

  // Use parseDiagnostics to find syntax errors.
  // Note: parseDiagnostics is an internal property of the SourceFile object
  // generated by the TypeScript compiler. We use it here to perform immediate
  // syntax verification before any file writes.
  const diagnostics = (
    sourceFile as ts.SourceFile & { parseDiagnostics: ts.Diagnostic[] }
  ).parseDiagnostics;
  if (diagnostics && diagnostics.length > 0) {
    const messages = diagnostics.map((d: ts.Diagnostic) => {
      if (d.start !== undefined) {
        const { line, character } = ts.getLineAndCharacterOfPosition(
          sourceFile,
          d.start,
        );
        const message = ts.flattenDiagnosticMessageText(d.messageText, '\n');
        return `Syntax error at ${line + 1}:${character + 1}: ${message}`;
      }
      return ts.flattenDiagnosticMessageText(d.messageText, '\n');
    });

    return {
      valid: false,
      error: messages.join('\n'),
    };
  }

  return { valid: true };
}

/**
 * Maps file extensions to TypeScript ScriptKind.
 */
function getScriptKind(ext: string): ts.ScriptKind {
  switch (ext) {
    case '.ts':
      return ts.ScriptKind.TS;
    case '.tsx':
      return ts.ScriptKind.TSX;
    case '.js':
      return ts.ScriptKind.JS;
    case '.jsx':
      return ts.ScriptKind.JSX;
    default:
      return ts.ScriptKind.Unknown;
  }
}

/**
 * Finds a specific node in the AST by its text content and type.
 * This is a foundational utility for the AST-based replacement strategy.
 */
export function findNodeByText(
  sourceFile: ts.SourceFile,
  text: string,
): ts.Node | undefined {
  let foundNode: ts.Node | undefined;

  function visit(node: ts.Node) {
    if (foundNode) return;

    // Check if the node's full text matches (handling some normalization)
    const nodeText = node.getText(sourceFile);
    if (normalizeText(nodeText) === normalizeText(text)) {
      foundNode = node;
      return;
    }

    ts.forEachChild(node, visit);
  }

  visit(sourceFile);
  return foundNode;
}

/**
 * Normalizes text by trimming and collapsing whitespace for more robust matching.
 */
function normalizeText(text: string): string {
  return text.trim().replace(/\s+/g, ' ');
}
