/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { describe, it, expect } from 'vitest';
import { generatePolicyToml, getSandboxCommand } from './policyWriter.js';
import {
  ProjectType,
  SandboxMethod,
  type WizardData,
} from '../ui/components/sandbox/types.js';

describe('policyWriter', () => {
  describe('generatePolicyToml', () => {
    it('should generate valid TOML for a web app project', () => {
      const data: WizardData = {
        projectType: ProjectType.WEB_APP,
        permissions: {
          fileRead: 'allow',
          fileWrite: 'ask_user',
          shellCommands: 'ask_user',
          webSearch: 'allow',
          webFetch: 'allow',
          mcpServers: 'ask_user',
        },
        sandboxMethod: SandboxMethod.NONE,
      };

      const toml = generatePolicyToml(data);

      expect(toml).toContain('# Generated by Sandbox Wizard');
      expect(toml).toContain('# Project type: web_app');
      expect(toml).toContain('[[rule]]');
      expect(toml).toContain('decision = "allow"');
      expect(toml).toContain('decision = "ask_user"');
      expect(toml).toContain(
        'toolName = ["glob", "grep_search", "list_directory", "read_file"]',
      );
    });

    it('should include deny rules for CLI tool project', () => {
      const data: WizardData = {
        projectType: ProjectType.CLI_TOOL,
        permissions: {
          fileRead: 'allow',
          fileWrite: 'ask_user',
          shellCommands: 'ask_user',
          webSearch: 'allow',
          webFetch: 'deny',
          mcpServers: 'deny',
        },
        sandboxMethod: SandboxMethod.DOCKER,
      };

      const toml = generatePolicyToml(data);

      expect(toml).toContain('decision = "deny"');
      expect(toml).toContain('# Sandbox method: docker');
    });

    it('should include correct priority values', () => {
      const data: WizardData = {
        projectType: ProjectType.CUSTOM,
        permissions: {
          fileRead: 'allow',
          fileWrite: 'ask_user',
          shellCommands: 'deny',
          webSearch: 'allow',
          webFetch: 'ask_user',
          mcpServers: 'deny',
        },
        sandboxMethod: SandboxMethod.NONE,
      };

      const toml = generatePolicyToml(data);

      // Allow rules get priority 50
      expect(toml).toContain('priority = 50');
      // Ask user rules get priority 10
      expect(toml).toContain('priority = 10');
      // Deny rules get priority 100
      expect(toml).toContain('priority = 100');
    });

    it('should handle all permissions set to allow', () => {
      const data: WizardData = {
        projectType: ProjectType.DATA_SCIENCE,
        permissions: {
          fileRead: 'allow',
          fileWrite: 'allow',
          shellCommands: 'allow',
          webSearch: 'allow',
          webFetch: 'allow',
          mcpServers: 'allow',
        },
        sandboxMethod: SandboxMethod.NONE,
      };

      const toml = generatePolicyToml(data);

      expect(toml).not.toContain('decision = "deny"');
      expect(toml).not.toContain('decision = "ask_user"');
    });
  });

  describe('getSandboxCommand', () => {
    it('should return docker for Docker method', () => {
      expect(getSandboxCommand(SandboxMethod.DOCKER)).toBe('docker');
    });

    it('should return sandbox-exec for Seatbelt method', () => {
      expect(getSandboxCommand(SandboxMethod.SEATBELT)).toBe('sandbox-exec');
    });

    it('should return runsc for gVisor method', () => {
      expect(getSandboxCommand(SandboxMethod.GVISOR)).toBe('runsc');
    });

    it('should return null for None method', () => {
      expect(getSandboxCommand(SandboxMethod.NONE)).toBeNull();
    });
  });
});
