/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import type {
  WizardData,
  ToolPermissions,
  PolicyDecisionValue,
} from '../ui/components/sandbox/types.js';
import { SandboxMethod } from '../ui/components/sandbox/types.js';

interface ToolRule {
  toolName: string | string[];
  decision: PolicyDecisionValue;
  priority: number;
}

const TOOL_MAPPINGS: Record<keyof ToolPermissions, string | string[]> = {
  fileRead: ['glob', 'grep_search', 'list_directory', 'read_file'],
  fileWrite: ['write_file', 'replace'],
  shellCommands: 'run_shell_command',
  webSearch: 'google_web_search',
  webFetch: 'web_fetch',
  mcpServers: 'mcp_*',
};

const PRIORITY_MAP: Record<PolicyDecisionValue, number> = {
  allow: 50,
  ask_user: 10,
  deny: 100,
};

const PERMISSION_KEYS: Array<keyof ToolPermissions> = [
  'fileRead',
  'fileWrite',
  'shellCommands',
  'webSearch',
  'webFetch',
  'mcpServers',
];

function permissionsToRules(permissions: ToolPermissions): ToolRule[] {
  const rules: ToolRule[] = [];

  for (const key of PERMISSION_KEYS) {
    const toolName = TOOL_MAPPINGS[key];
    const decision = permissions[key];
    rules.push({
      toolName,
      decision,
      priority: PRIORITY_MAP[decision],
    });
  }

  return rules;
}

function formatToolName(toolName: string | string[]): string {
  if (Array.isArray(toolName)) {
    return `[${toolName.map((t) => `"${t}"`).join(', ')}]`;
  }
  return `"${toolName}"`;
}

export function generatePolicyToml(data: WizardData): string {
  const rules = permissionsToRules(data.permissions);
  const lines: string[] = [];

  lines.push(
    '# Generated by Sandbox Wizard',
    `# Project type: ${data.projectType}`,
    `# Sandbox method: ${data.sandboxMethod}`,
    '#',
    '# Priority bands:',
    '# - Workspace policies: 3 + priority/1000',
    '# Higher priority numbers take precedence',
    '',
  );

  for (const rule of rules) {
    lines.push('[[rule]]');
    lines.push(`toolName = ${formatToolName(rule.toolName)}`);
    lines.push(`decision = "${rule.decision}"`);
    lines.push(`priority = ${rule.priority}`);
    lines.push('');
  }

  return lines.join('\n');
}

export function getSandboxCommand(method: SandboxMethod): string | null {
  switch (method) {
    case SandboxMethod.DOCKER:
      return 'docker';
    case SandboxMethod.SEATBELT:
      return 'sandbox-exec';
    case SandboxMethod.GVISOR:
      return 'runsc';
    case SandboxMethod.NONE:
      return null;
    default:
      return null;
  }
}
