/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { describe, expect, it } from 'vitest';
import { renderMermaidAscii } from './ascii.js';

describe('renderMermaidAscii', () => {
  it('renders aliased sequence diagrams without duplicating raw participant ids', () => {
    const spec = `
sequenceDiagram
    participant State as Component State/Props
    participant VDOM_New as New Virtual DOM
    participant Reconciler as Fiber Reconciler
    State->>VDOM_New: Trigger Update / Re-render
    Reconciler->>State: Compare New vs. Old
`.trim();

    const output = renderMermaidAscii(spec, 90);
    expect(output).toContain('Sequence Diagram');
    expect(output).toContain('Component State/Props');
    expect(output).toContain('New Virtual DOM');
    expect(output).not.toContain('• State');
    expect(output).not.toContain('• VDOM_New');
  });

  it('renders labeled flowchart branches generated by explain prompts', () => {
    const spec = `
graph TD
    CalcGrad --> Check{Convergence?}
    Check -- No --> Update[Update Theta]
    Check -- Yes --> End([Minimum Found / End])
`.trim();

    const output = renderMermaidAscii(spec, 100);
    expect(output).toContain('Convergence?');
    expect(output).toContain('Update Theta');
    expect(output).toContain('Minimum Found / End');
    expect(output).toContain('No');
    expect(output).toContain('Yes');
  });
});
