name: 'Setup and Test'

on:
  workflow_call:
    inputs:
      ref:
        description: 'The branch or ref to checkout.'
        required: true
        type: 'string'
      force_skip_tests:
        description: 'Whether to force skip tests.'
        required: false
        type: 'boolean'
        default: false
    secrets:
      GEMINI_API_KEY:
        required: false

jobs:
  test:
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8' # ratchet:actions/checkout@v5
        with:
          ref: '${{ inputs.ref }}'
          fetch-depth: 0

      - name: 'Setup Node.js'
        uses: 'actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020' # ratchet:actions/setup-node@v4
        with:
          node-version-file: '.nvmrc'
          cache: 'npm'

      - name: 'Install Dependencies'
        run: npm ci

      - name: 'Run Tests'
        if: ${{ !inputs.force_skip_tests }}
        env:
          GEMINI_API_KEY: '${{ secrets.GEMINI_API_KEY }}'
        run: |-
          npm run preflight
          npm run test:integration:sandbox:none
          npm run test:integration:sandbox:docker
