import json
import datetime
import os
from google.cloud import storage
from google.antigravity.types import Text

BUCKET_NAME = os.environ.get("TRIAGE_DEBUG_LOGS_BUCKET")

def upload_to_bucket(repository: str, issue_number: str, payload: str):
    """
    Uploads a string payload directly to the triage debug logs GCS bucket.
    """
    if not payload:
        return
    try:
        storage_client = storage.Client()
        bucket = storage_client.bucket(BUCKET_NAME)
        
        timestamp = datetime.datetime.now(datetime.timezone.utc).strftime("%Y%m%d_%H%M%S")
        safe_repo = repository.replace("/", "_")
        blob_name = f"{safe_repo}/issue_{issue_number}_{timestamp}_debug.log"
        
        blob = bucket.blob(blob_name)
        blob.upload_from_string(payload, content_type="text/plain")
        print(f"[LOGIC] Uploaded debug logs to gs://{BUCKET_NAME}/{blob_name}")
    except Exception as e:
        print(f"[LOGIC] Error uploading debug logs to GCS: {e}")

def upload_agent_run_logs(repository: str, issue_number: str, resolved_chunks):
    """
    Serializes the Antigravity Agent resolved stream chunks to JSON and uploads them to GCS.
    """
    if not resolved_chunks:
        return
    # Format chunks into a serializable format
    try:
        serializable = []
        for chunk in resolved_chunks:
            try:
                dumped = chunk.model_dump()
            except AttributeError:
                dumped = chunk.dict()
            dumped["chunk_type"] = chunk.__class__.__name__
            serializable.append(dumped)
            
        debug_log_str = json.dumps(serializable, indent=2, default=str)
        upload_to_bucket(repository, issue_number, debug_log_str)
    except Exception as e:
        print(f"[LOGIC] Error serializing/uploading agent debug logs: {e}")

def extract_final_output(resolved_chunks) -> str:
    """
    Extracts the final response text generated by the agent during the last execution step.
    
    Since the agent outputs conversational planning text during its tool-calling turns,
    this function isolates the final turn (highest step_index) and filters for text chunks,
    stripping away any intermediate planning text, thoughts, or markdown backticks around the JSON.
    """
    # Filter for Text chunks (skip Thought and ToolCall chunks)
    text_chunks = [c for c in resolved_chunks if isinstance(c, Text)]
    if not text_chunks:
        return ""
    
    # Final output is in the last step
    last_step = text_chunks[-1].step_index
    return "".join(c.text for c in text_chunks if c.step_index == last_step).strip()