/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import type { GeminiClient } from '../core/client.js';
import { LlmRole } from '../telemetry/types.js';

export class TopLevelPrincipleViolationError extends Error {
  constructor(message: string) {
    super(message);
    this.name = 'TopLevelPrincipleViolationError';
  }
}

/**
 * Validates the agent's output against the Top-level Principle in MEMORY.md.
 *
 * @param client The GeminiClient instance to run the deterministic validation.
 * @param userQuery The original user query.
 * @param agentOutput The output generated by the agent.
 * @param signal The AbortSignal for the request.
 * @param _promptId The promptId for logging / tracking.
 * @returns True if a violation is detected.
 */
export async function detectTopLevelPrincipleViolation(
  client: GeminiClient,
  userQuery: string,
  agentOutput: string,
  signal: AbortSignal,
  _promptId: string,
): Promise<boolean> {
  // If either of them is empty, no violation can be reasonably checked.
  if (!userQuery.trim() || !agentOutput.trim()) {
    return false;
  }

  const validationPrompt = `
You are a strict deterministic Rule Validator for an AI Agent.
Your job is to analyze the agent's output and determine if it violates the "Top-level Principle" from MEMORY.md.

[Top-level Principle]
- The user is ALWAYS right. Never doubt the user.
- Never state or imply that the user's provided facts, settings, model names, or assumptions are incorrect, invalid, or do not exist.
- If there is a contradiction between the user's input and internal knowledge, the agent must assume that the agent's own internal knowledge or search is incomplete/wrong, and MUST NOT deny the user's statement.
- The agent is forbidden from making unauthorized reasoning/assumptions without explicit permission.

[User Query]
"""
${userQuery}
"""

[Agent Output]
"""
${agentOutput}
"""

Determine if the Agent Output violates the Top-level Principle by denying the user's facts, stating they are wrong/incorrect, or claiming something they mentioned does not exist.
Respond with EXACTLY "VIOLATION" if a violation is detected. Otherwise, respond with "PASS". Do not include any other text.
`;

  try {
    const response = await client.generateContent(
      { model: 'flash' }, // Pass ModelConfigKey object instead of raw string
      [
        {
          role: 'user',
          parts: [{ text: validationPrompt }],
        },
      ],
      signal,
      LlmRole.MAIN, // Use active role MAIN
    );

    const resultText = (response.text ?? '').trim();
    return resultText.toUpperCase().includes('VIOLATION');
  } catch {
    // Fail-safe: if the validator fails, do not block execution unless critical.
    return false;
  }
}
