name: 'docs_pr_check'

on:
  pull_request:
    paths-ignore:
      - 'docs/**'

jobs:
  docs_pr_check:
    runs-on: 'ubuntu-latest'
    steps:
      - run: "echo 'Bypassing docs_pr_check because docs/ was not changed.'"
