name: 'Evals'

on:
  push:
    branches:
      - 'main'
  merge_group:

jobs:
  evals-macos:
    name: 'Evals'
    runs-on: 'ubuntu-latest'
    strategy:
      matrix:
        node-version:
          - '20.x'
          - '22.x'
          - '24.x'
    steps:
      - name: 'Checkout'
        uses: 'actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8' # ratchet:actions/checkout@v5

      - name: 'Set up Node.js ${{ matrix.node-version }}'
        uses: 'actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020' # ratchet:actions/setup-node@v4
        with:
          node-version: '${{ matrix.node-version }}'
          cache: 'npm'

      - name: 'Set up Python'
        uses: 'actions/setup-python@v5.6.0' # ratchet:actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: 'Install and configure Poetry'
        uses: 'snok/install-poetry@v1.4.1' # ratchet:snok/install-poetry@v1