name: 'Eval'

on:
  workflow_dispatch:
    inputs:
      branch-or-commit:
        description: 'The branch or commit to run the evaluation on.'
        required: true
        type: 'string'
      dry-run:
        description: 'dry run: runs evaluation without creating an issue.'
        required: false
        type: 'boolean'
        default: true
      resolution-rate-threshold:
        description: 'The threshold for the resolution rate.'
        required: false
        type: 'number'
        default: 90
      tool-success-rate-threshold:
        description: 'The threshold for the tool success rate.'
        required: false
        type: 'number'
        default: 80

defaults:
  run:
    shell: 'bash'

permissions:
  contents: 'read'
  id-token: 'write'
  packages: 'read'
  issues: 'write'

jobs:
  eval:
    name: 'Eval'
    if: >-
      github.repository == 'google-gemini/gemini-cli'
    runs-on: 'ubuntu-latest'
    container:
      image: 'ghcr.io/google-gemini/gemini-cli-swe-agent-eval@sha256:cd5edc4afd2245c1f575e791c0859b3c084a86bb3bd9a6762296da5162b35a8f'
      credentials:
        username: '${{ github.actor }}'
        password: '${{ secrets.GITHUB_TOKEN }}'
      env:
        GITHUB_TOKEN: '${{ secrets.GITHUB_TOKEN }}'
        DEFAULT_VERTEXAI_PROJECT: '${{ vars.GOOGLE_CLOUD_PROJECT }}'
        GOOGLE_CLOUD_PROJECT: '${{ vars.GOOGLE_CLOUD_PROJECT }}'
        GEMINI_API_KEY: '${{ secrets.EVAL_GEMINI_API_KEY }}'
        GCLI_LOCAL_FILE_TELEMETRY: 'true'
    steps:
      - name: 'Run evaluation'
        uses: './.github/actions/run-evaluation'
        with:
          branch-or-commit: '${{ inputs.branch-or-commit }}'
          dry-run: '${{ inputs.dry-run }}'
          resolution-rate-threshold: '${{ inputs.resolution-rate-threshold }}'
          tool-success-rate-threshold: '${{ inputs.tool-success-rate-threshold }}'
          github-token: '${{ secrets.GITHUB_TOKEN }}'
          google-cloud-project: '${{ vars.GOOGLE_CLOUD_PROJECT }}'
          gcp-wif-provider: '${{ vars.GCP_WIF_PROVIDER }}'
          service-account-email: '${{ vars.SERVICE_ACCOUNT_EMAIL }}'
          eval-gemini-api-key: '${{ secrets.EVAL_GEMINI_API_KEY }}'
          eval-gcs-bucket: '${{ vars.EVAL_GCS_ARTIFACTS_BUCKET }}'
