name: 'Eval'

on:
  workflow_dispatch:

defaults:
  run:
    shell: 'bash'

jobs:
  trigger-bench-hub:
    name: 'Trigger BenchHub E2E'
    if: >-
      github.repository == 'google-gemini/gemini-cli'
    runs-on: 'ubuntu-latest'
    steps:
      - name: 'Generate token'
        id: 'generate_token'
        uses: 'actions/create-github-app-token@fee1f7d63c2ff003460e3d139729b119787bc349' # ratchet:actions/create-github-app-token@v2
        with:
          app-id: '${{ secrets.APP_ID }}'
          private-key: '${{ secrets.PRIVATE_KEY }}'
          owner: 'googlecloud-appeco-incubator'
          repositories: 'bench-hub'

      - name: 'Repository Dispatch'
        uses: 'peter-evans/repository-dispatch@ff45666b9427631e3450c54a1bcbee4d9ff4d7c0' # ratchet:peter-evans/repository-dispatch@v3
        with:
          token: '${{ steps.generate_token.outputs.token }}'
          repository: 'googlecloud-appeco-incubator/bench-hub'
          event-type: 'gemini_cli_updated'
          client-payload: '{"branch": "${{ github.ref_name }}"}'
