name: 'Promote Release'

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: 'Run a dry-run of the release process; no branches, npm packages or GitHub releases will be created.'
        required: true
        type: 'boolean'
        default: true

jobs:
  promote:
    runs-on: 'ubuntu-latest'
    environment:
      name: 'production-release'
    permissions:
      contents: 'write'
      packages: 'write'
      id-token: 'write'
      issues: 'write'
      pull-requests: 'write'

    steps:
      - name: 'Get main SHA'
        id: 'main_sha'
        run: echo "SHA=$(git rev-parse main)" >> $GITHUB_OUTPUT

      - name: 'Get latest preview tag'
        id: 'preview_tag'
        run: echo "TAG=$(git describe --tags --abbrev=0 --match 'v*-preview')" >> $GITHUB_OUTPUT

      - name: 'Get Stable Version'
        id: 'stable_version'
        run: |
          VERSION_JSON=$(node scripts/get-release-version.js --type stable --version ${{ steps.preview_tag.outputs.TAG }})
          echo "RELEASE_TAG=$(echo "${VERSION_JSON}" | jq -r .releaseTag)" >> "${GITHUB_OUTPUT}"
          echo "RELEASE_VERSION=$(echo "${VERSION_JSON}" | jq -r .releaseVersion)" >> "${GITHUB_OUTPUT}"
          echo "NPM_TAG=$(echo "${VERSION_JSON}" | jq -r .npmTag)" >> "${GITHUB_OUTPUT}"
          echo "PREVIOUS_TAG=$(echo "${VERSION_JSON}" | jq -r .previousReleaseTag)" >> "${GITHUB_OUTPUT}"

      - name: 'Promote Preview to Stable'
        uses: ./.github/workflows/reusable/build-and-publish.yml
        with:
          ref: ${{ steps.preview_tag.outputs.TAG }}
          release_version: ${{ steps.stable_version.outputs.RELEASE_VERSION }}
          npm_tag: ${{ steps.stable_version.outputs.NPM_TAG }}
          dry_run: ${{ github.event.inputs.dry_run }}
        secrets:
          WOMBAT_TOKEN_CORE: ${{ secrets.WOMBAT_TOKEN_CORE }}
          WOMBAT_TOKEN_CLI: ${{ secrets.WOMBAT_TOKEN_CLI }}

      - name: 'Create Stable GitHub Release'
        uses: ./.github/workflows/reusable/create-github-release.yml
        with:
          release_tag: ${{ steps.stable_version.outputs.RELEASE_TAG }}
          release_branch: ${{ steps.preview_tag.outputs.TAG }}
          previous_tag: ${{ steps.stable_version.outputs.PREVIOUS_TAG }}
          dry_run: ${{ github.event.inputs.dry_run }}

      - name: 'Get Preview Version'
        id: 'preview_version'
        run: |
          VERSION_JSON=$(node scripts/get-release-version.js --type preview --version ${{ steps.stable_version.outputs.RELEASE_TAG }})
          echo "RELEASE_TAG=$(echo "${VERSION_JSON}" | jq -r .releaseTag)" >> "${GITHUB_OUTPUT}"
          echo "RELEASE_VERSION=$(echo "${VERSION_JSON}" | jq -r .releaseVersion)" >> "${GITHUB_OUTPUT}"
          echo "NPM_TAG=$(echo "${VERSION_JSON}" | jq -r .npmTag)" >> "${GITHUB_OUTPUT}"
          echo "PREVIOUS_TAG=$(echo "${VERSION_JSON}" | jq -r .previousReleaseTag)" >> "${GITHUB_OUTPUT}"

      - name: 'Create Next Preview from main'
        uses: ./.github/workflows/reusable/build-and-publish.yml
        with:
          ref: ${{ steps.main_sha.outputs.SHA }}
          release_version: ${{ steps.preview_version.outputs.RELEASE_VERSION }}
          npm_tag: ${{ steps.preview_version.outputs.NPM_TAG }}
          dry_run: ${{ github.event.inputs.dry_run }}
        secrets:
          WOMBAT_TOKEN_CORE: ${{ secrets.WOMBAT_TOKEN_CORE }}
          WOMBAT_TOKEN_CLI: ${{ secrets.WOMBAT_TOKEN_CLI }}

      - name: 'Create Preview GitHub Release'
        uses: ./.github/workflows/reusable/create-github-release.yml
        with:
          release_tag: ${{ steps.preview_version.outputs.RELEASE_TAG }}
          release_branch: ${{ steps.main_sha.outputs.SHA }}
          previous_tag: ${{ steps.stable_version.outputs.RELEASE_TAG }}
          dry_run: ${{ github.event.inputs.dry_run }}

      - name: 'Prepare main for Next Nightly'
        if: ${{ !github.event.inputs.dry_run }}
        run: |
          NEXT_NIGHTLY_VERSION=$(node -e "console.log(require('./scripts/get-release-version.js').calculateNextVersion('${{ steps.preview_version.outputs.RELEASE_VERSION }}'))")
          git checkout ${{ steps.main_sha.outputs.SHA }}
          git checkout -b release/prepare-nightly-${NEXT_NIGHTLY_VERSION}
          npm run release:version ${NEXT_NIGHTLY_VERSION}
          git add .
          git commit -m "chore(release): Prepare for next nightly version ${NEXT_NIGHTLY_VERSION}"
          git push -u origin release/prepare-nightly-${NEXT_NIGHTLY_VERSION}
          gh pr create --title "chore(release): Prepare for next nightly version ${NEXT_NIGHTLY_VERSION}" --body "Automated PR to update the version in main." --base main
          gh pr merge --auto --merge
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}