name: Promote Release

on:
  workflow_dispatch:
    inputs:
      ref:
        description: 'The branch, tag, or SHA to checkout. Defaults to main.'
        required: true
        default: 'main'
      dry_run:
        description: 'Run a dry-run of the release process; no branches, npm packages or GitHub releases will be created.'
        required: true
        type: 'boolean'
        default: true

jobs:
  calculate-versions:
    name: Calculate Release Versions
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.ref }}
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install Dependencies
        run: npm ci

      - name: Get latest preview tag
        id: preview_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(gh release list --limit 100 --json tagName | jq -r '[.[] | select(.tagName | contains("preview"))] | .[0].tagName')
          echo "LATEST_PREVIEW_TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Get latest stable tag
        id: stable_tag
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG=$(gh release list --limit 100 --json tagName | jq -r '[.[] | select(.tagName | (contains("nightly") or contains("preview")) | not)] | .[0].tagName')
          echo "LATEST_STABLE_TAG=$TAG" >> $GITHUB_OUTPUT

      - name: Calculate versions
        id: versions
        run: |
          CURRENT_VERSION=$(node -p "require('./package.json').version")
          echo "Current version from package.json: $CURRENT_VERSION"

          # Extract major and minor versions
          MAJOR=$(echo $CURRENT_VERSION | cut -d. -f1)
          MINOR=$(echo $CURRENT_VERSION | cut -d. -f2)

          # Calculate next nightly version (minor bump)
          # e.g., 0.6.x -> 0.7.0-nightly
          NEXT_MINOR=$((MINOR + 1))
          NEXT_NIGHTLY_VERSION="$MAJOR.$NEXT_MINOR.0-nightly"

          # Calculate next preview version
          # e.g., 0.6.x -> 0.6.0-preview
          NEXT_PREVIEW_VERSION="$MAJOR.$MINOR.0-preview"

          # Calculate next stable version (minor decrement)
          # e.g., 0.6.x -> 0.5.0
          PREVIOUS_MINOR=$((MINOR - 1))
          NEXT_STABLE_VERSION="$MAJOR.$PREVIOUS_MINOR.0"

          STABLE_RELEASE_TAG=$(echo "${{ steps.preview_tag.outputs.LATEST_PREVIEW_TAG }}" | sed 's/-preview.*//')
          STABLE_RELEASE_VERSION=$(echo "$STABLE_RELEASE_TAG" | sed 's/^v//')

          echo "next_nightly_version=$NEXT_NIGHTLY_VERSION" >> $GITHUB_OUTPUT
          echo "next_preview_version=$NEXT_PREVIEW_VERSION" >> $GITHUB_OUTPUT
          echo "next_stable_version=$NEXT_STABLE_VERSION" >> $GITHUB_OUTPUT
          echo "stable_release_tag=$STABLE_RELEASE_TAG" >> $GITHUB_OUTPUT
          echo "stable_release_version=$STABLE_RELEASE_VERSION" >> $GITHUB_OUTPUT
          echo "stable_npm_tag=latest" >> $GITHUB_OUTPUT
          echo "stable_previous_tag=${{ steps.stable_tag.outputs.LATEST_STABLE_TAG }}" >> $GITHUB_OUTPUT

      - name: Print calculated versions
        run: |
          echo "Dry Run: ${{ github.event.inputs.dry_run }}"
          echo "---"
          echo "Current Preview Tag: ${{ steps.preview_tag.outputs.LATEST_PREVIEW_TAG }}"
          echo "Current Stable Tag: ${{ steps.stable_tag.outputs.LATEST_STABLE_TAG }}"
          echo "---"
          echo "Promoting to Stable Release"
          echo "  Release Tag: ${{ steps.versions.outputs.stable_release_tag }}"
          echo "  Release Version: ${{ steps.versions.outputs.stable_release_version }}"
          echo "  NPM Tag: ${{ steps.versions.outputs.stable_npm_tag }}"
          echo "  Previous Tag for Release Notes: ${{ steps.versions.outputs.stable_previous_tag }}"
          echo "---"
          echo "Next Nightly Version: ${{ steps.versions.outputs.next_nightly_version }}"
          echo "Next Preview Version: ${{ steps.versions.outputs.next_preview_version }}"
          echo "Next Stable Version (from nightly): ${{ steps.versions.outputs.next_stable_version }}"

      - name: Configure Git User
        if: ${{ github.event.inputs.dry_run == 'false' }}
        run: |
          git config user.name "gemini-cli-robot"
          git config user.email "gemini-cli-robot@google.com"

      - name: Create and switch to a release branch
        if: ${{ github.event.inputs.dry_run == 'false' }}
        id: release_branch
        run: |
          BRANCH_NAME="promote/${{ steps.versions.outputs.stable_release_tag }}"
          git switch -c "${{ BRANCH_NAME }}"
          echo "BRANCH_NAME=${{ BRANCH_NAME }}" >> "${{ GITHUB_OUTPUT }}"

      - name: Update package versions
        if: ${{ github.event.inputs.dry_run == 'false' }}
        run: |
          npm run release:version ${{ steps.versions.outputs.stable_release_version }}

      - name: Commit and Push package versions
        if: ${{ github.event.inputs.dry_run == 'false' }}
        env:
          BRANCH_NAME: ${{ steps.release_branch.outputs.BRANCH_NAME }}
        run: |
          git add package.json package-lock.json packages/*/package.json
          git commit -m "chore(release): ${{ steps.versions.outputs.stable_release_tag }}"
          git push --set-upstream origin "${{ BRANCH_NAME }}"

      - name: Create Pull Request
        if: ${{ github.event.inputs.dry_run == 'false' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.release_branch.outputs.BRANCH_NAME }}
        run: |
          gh pr create \
            --title "chore(release): Promote ${{ steps.versions.outputs.stable_release_tag }}" \
            --body "Automated PR to promote ${{ steps.versions.outputs.stable_release_tag }} to stable." \
            --base "${{ github.event.inputs.ref }}" \
            --head "${{ BRANCH_NAME }}"

      - name: Enable Auto-Merge
        if: ${{ github.event.inputs.dry_run == 'false' }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH_NAME: ${{ steps.release_branch.outputs.BRANCH_NAME }}
        run: |
          gh pr merge "${{ BRANCH_NAME }}" --auto --squash