name: Test Secrets If
on:
  workflow_dispatch:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check Secret
        if: ${{ secrets.APP_ID != '' }}
        run: echo "Secret is not empty"
      - name: Check Secret 2
        if: secrets.APP_ID != ''
        run: echo "Secret is not empty 2"
