name: 'Trigger E2E'

on:
  pull_request_target:
    types: ['labeled']
jobs:
  trigger_e2e:
    name: 'Trigger e2e'
    runs-on: 'gemini-cli-ubuntu-16-core'
    steps:
      - id: 'trigger-e2e'
        run: |
          echo "Trigger e2e workflow"
