/**
 * @license
 * Copyright 2026 Google LLC
 * SPDX-License-Identifier: Apache-2.0
 */

import { z } from 'zod';
import { zodToJsonSchema } from 'zod-to-json-schema';
import type { Config } from '../config/config.js';
import type { SerializableConfirmationDetails } from '../confirmation-bus/types.js';
import { getResponseText } from '../utils/partUtils.js';
import { safeTemplateReplace } from '../utils/textUtils.js';
import { DEFAULT_GEMINI_FLASH_LITE_MODEL } from '../config/models.js';
import { debugLogger } from '../utils/debugLogger.js';
import { isSafeRegExp } from './utils.js';
import {
  LlmRole,
  logPolicySuggestion,
  PolicySuggestionEvent,
} from '../telemetry/index.js';

/**
 * A suggested policy rule generated by an LLM for tool approval scoping.
 */
export interface PolicySuggestion {
  /** Human-readable description shown to the user, e.g. "Allow git read-only commands" */
  description: string;
  /** For shell commands: the command prefix(es) to allow */
  commandPrefix?: string | string[];
  /** Alternative: a regex pattern for args matching */
  argsPattern?: string;
  /** For MCP tools: the tool name pattern to scope */
  toolName?: string;
}

const PolicySuggestionSchema = z.object({
  description: z.string(),
  commandPrefix: z.union([z.string(), z.array(z.string())]).optional(),
  argsPattern: z.string().optional(),
  toolName: z.string().optional(),
});

const SUGGESTION_PROMPT = `You are a security policy advisor for a CLI tool. A user just approved a tool invocation and wants to create a reusable "allow" rule. Your job is to suggest a well-scoped rule that is broader than the exact invocation but narrower than allowing everything.

### Tool invocation context
Type: {{tool_type}}
{{tool_context}}

### Instructions
1. Analyze whether this tool invocation is read-only, write/destructive, or side-effecting.
2. Suggest a policy scope that groups similar safe operations together.
3. For shell commands: suggest a commandPrefix (string or array of strings) that covers the family of safe commands the user likely wants to allow. For example, if the user ran "git diff src/main.ts", suggest commandPrefix ["git diff", "git log", "git status", "git show"] rather than just "git diff src/main.ts".
4. For file edits: suggest a description of the scope (e.g. "files in src/components/").
5. For MCP tools: suggest the toolName to scope.
6. Keep the description concise (under 80 characters).
7. Err on the side of being conservative — only group operations that are clearly in the same safety category.
8. NEVER suggest allowing destructive commands (rm, git push, git reset --hard, DROP TABLE, etc.) as part of a broader scope. Those should remain exact-match only.

### Output
Return a JSON object with:
- "description": A short human-readable summary of the suggested scope
- "commandPrefix": (optional) string or array of command prefixes to allow
- "argsPattern": (optional) a regex pattern for argument matching — only use this if commandPrefix is insufficient
- "toolName": (optional) for MCP tool name scoping
`;

/**
 * Builds the tool-specific context string for the prompt.
 */
function buildToolContext(details: SerializableConfirmationDetails): string {
  switch (details.type) {
    case 'exec': {
      const lines = [`Command: ${details.command}`];
      if (details.rootCommand) {
        lines.push(`Root command: ${details.rootCommand}`);
      }
      if (details.rootCommands && details.rootCommands.length > 0) {
        lines.push(
          `Root commands (parsed): ${details.rootCommands.join(', ')}`,
        );
      }
      if (details.commands && details.commands.length > 1) {
        lines.push(`All commands:\n${details.commands.join('\n')}`);
      }
      return lines.join('\n');
    }
    case 'edit':
      return `File: ${details.fileName}\nPath: ${details.filePath}`;
    case 'mcp': {
      const lines = [
        `Server: ${details.serverName}`,
        `Tool: ${details.toolName}`,
      ];
      if (details.toolDescription) {
        lines.push(`Description: ${details.toolDescription}`);
      }
      if (details.toolArgs) {
        try {
          lines.push(`Arguments: ${JSON.stringify(details.toolArgs)}`);
        } catch {
          // Skip unserializable args
        }
      }
      return lines.join('\n');
    }
    case 'info':
      return `Prompt: ${details.prompt}${details.urls ? `\nURLs: ${details.urls.join(', ')}` : ''}`;
    default:
      return '';
  }
}

/**
 * Uses Gemini Flash Lite to suggest a well-scoped policy rule for a tool approval.
 *
 * Returns null on any failure (fail-open pattern).
 */
export async function suggestPolicyScope(
  confirmationDetails: SerializableConfirmationDetails,
  toolName: string,
  config: Config,
): Promise<PolicySuggestion | null> {
  const contentGenerator = config.getContentGenerator();
  if (!contentGenerator) {
    debugLogger.debug(
      '[PolicySuggestion] Skipped: content generator not available',
    );
    return null;
  }

  // Only generate suggestions for actionable tool types
  if (
    confirmationDetails.type === 'ask_user' ||
    confirmationDetails.type === 'exit_plan_mode'
  ) {
    return null;
  }

  const toolContext = buildToolContext(confirmationDetails);
  if (!toolContext) {
    return null;
  }

  const TIMEOUT_MS = 5000;

  try {
    // Time-box the Flash Lite call — the user may confirm before it responds.
    let timeoutId: NodeJS.Timeout;
    const timeoutPromise = new Promise<null>((resolve) => {
      timeoutId = setTimeout(() => resolve(null), TIMEOUT_MS);
    });
    const result = await Promise.race([
      contentGenerator.generateContent(
        {
          model: DEFAULT_GEMINI_FLASH_LITE_MODEL,
          config: {
            responseMimeType: 'application/json',
            responseSchema: zodToJsonSchema(PolicySuggestionSchema, {
              target: 'openApi3',
            }),
          },
          contents: [
            {
              role: 'user',
              parts: [
                {
                  text: safeTemplateReplace(SUGGESTION_PROMPT, {
                    tool_type: confirmationDetails.type,
                    tool_context: toolContext,
                  }),
                },
              ],
            },
          ],
        },
        'policy-suggestion',
        LlmRole.SUBAGENT,
      ),
      timeoutPromise,
    ]);
    clearTimeout(timeoutId!);

    if (!result) {
      debugLogger.debug('[PolicySuggestion] Timed out');
      return null;
    }

    const responseText = getResponseText(result);
    debugLogger.debug(`[PolicySuggestion] Raw response: ${responseText}`);

    if (!responseText) {
      debugLogger.debug('[PolicySuggestion] Empty response');
      return null;
    }

    try {
      const parsed = PolicySuggestionSchema.parse(JSON.parse(responseText));

      // Validate argsPattern if present
      if (parsed.argsPattern && !isSafeRegExp(parsed.argsPattern)) {
        debugLogger.debug(
          `[PolicySuggestion] Unsafe argsPattern rejected: ${parsed.argsPattern}`,
        );
        const safeSuggestion = {
          description: parsed.description,
          commandPrefix: parsed.commandPrefix,
          toolName: parsed.toolName,
        };
        logPolicySuggestion(
          config,
          new PolicySuggestionEvent(
            toolContext,
            JSON.stringify(safeSuggestion),
          ),
        );
        return safeSuggestion;
      }

      debugLogger.debug(`[PolicySuggestion] Parsed: ${JSON.stringify(parsed)}`);
      logPolicySuggestion(
        config,
        new PolicySuggestionEvent(toolContext, JSON.stringify(parsed)),
      );
      return parsed;
    } catch (parseError) {
      debugLogger.debug('[PolicySuggestion] Parse error:', parseError);
      logPolicySuggestion(
        config,
        new PolicySuggestionEvent(
          toolContext,
          '',
          parseError instanceof Error ? parseError.message : String(parseError),
        ),
      );
      return null;
    }
  } catch (error) {
    debugLogger.debug('[PolicySuggestion] LLM call failed:', error);
    logPolicySuggestion(
      config,
      new PolicySuggestionEvent(
        toolContext,
        '',
        error instanceof Error ? error.message : String(error),
      ),
    );
    return null;
  }
}
